# Generated by Django 3.2.4 on 2021-08-02 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emitidos', '0004_rename_denominacion_emisor_comprobantesemitidos_denominacion_receptor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobantesRecibidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Tipo', models.CharField(max_length=12)),
                ('Punto_de_Venta', models.IntegerField(verbose_name='Pto. Vta')),
                ('Numero_Desde', models.IntegerField(verbose_name='N° comp')),
                ('Cuit', models.IntegerField()),
                ('Denominacion_Emisor', models.CharField(max_length=120, verbose_name='Razón Social')),
                ('Tipo_Cambio', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('Moneda', models.CharField(default='$', max_length=120)),
                ('Imp_Neto_Gravado', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Imp_Neto_No_Gravado', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Imp_Op_Exentas', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('IVA', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Imp_Total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Neto_pesos', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Iva_pesos', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Total_pesos', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Alicuota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('Contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emitidos.contribuyente')),
            ],
            options={
                'verbose_name': 'Comprobante Recibido',
                'verbose_name_plural': 'Comprobantes Recibidos',
                'ordering': ['-Fecha'],
            },
        ),
    ]
