# Generated by Django 3.2.4 on 2021-07-23 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Razon_Social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('Cuit', models.IntegerField()),
                ('Actividades', models.TextField(blank=True, null=True, verbose_name='Actividades Económicas')),
                ('Fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Actividades')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Teléfono Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComprobantesEmitidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Tipo', models.CharField(max_length=12)),
                ('Punto_de_Venta', models.IntegerField()),
                ('Numero_Desde', models.IntegerField()),
                ('Cuit', models.IntegerField(max_length=120)),
                ('Denominacion_Emisor', models.CharField(max_length=120)),
                ('Tipo_Cambio', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('Moneda', models.CharField(default='$', max_length=120)),
                ('Imp_Neto_Gravado', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Imp_Neto_No_Gravado', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Imp_Op_Exentas', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('IVA', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Imp_Total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Neto_pesos', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Iva_pesos', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Total_pesos', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Alicuota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('Contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emitidos.contribuyente')),
            ],
        ),
    ]
