# Generated by Django 3.2.4 on 2021-07-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitidos', '0002_alter_comprobantesemitidos_cuit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprobantesemitidos',
            options={'ordering': ['-Fecha'], 'verbose_name': 'Comprobante Emitido', 'verbose_name_plural': 'Comprobantes Emitidos'},
        ),
        migrations.AlterModelOptions(
            name='contribuyente',
            options={'ordering': ['-created'], 'verbose_name': 'Contribuyente', 'verbose_name_plural': 'Contribuyentes'},
        ),
        migrations.AlterField(
            model_name='comprobantesemitidos',
            name='Denominacion_Emisor',
            field=models.CharField(max_length=120, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='comprobantesemitidos',
            name='Numero_Desde',
            field=models.IntegerField(verbose_name='N° comp'),
        ),
        migrations.AlterField(
            model_name='comprobantesemitidos',
            name='Punto_de_Venta',
            field=models.IntegerField(verbose_name='Pto. Vta'),
        ),
    ]
