# Generated by Django 3.2.4 on 2021-08-02 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emitidos', '0003_auto_20210731_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprobantesemitidos',
            old_name='Denominacion_Emisor',
            new_name='Denominacion_Receptor',
        ),
    ]
