# Generated by Django 3.2.4 on 2021-08-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emitidos', '0004_rename_denominacion_emisor_comprobantesemitidos_denominacion_receptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantesemitidos',
            name='Tipo',
            field=models.CharField(max_length=60),
        ),
    ]
